### ISSUE TITLE
Add some Features

### ISSUE THREAD

**Issue by Aditya-Narayan-Nayak** [AmanSarraf/Opensource-Buddy#45]
## Todo

- [ ] make the reach us section workable
- [ ] Automatic add the contributor in UI
- [ ] Add some good-looking UI in the Header section / you can completely change the header section Also

**Comment by AmanSarraf** [comment]
sure , Thanks @Aditya-Narayan-Nayak
